import type { CompetitionCategory } from "./categories";

/**
 * Banka fillestare e pyetjeve të garës.
 *
 * Pyetje me një përgjigje të vetme të saktë dhe pa varësi nga viti, që të mos
 * vjetërohen. Mbillen në bazë herën e parë që gara hapet (`ensureQuestionBank`).
 * Forma: [pyetja, katër alternativat, indeksi i saktë, vështirësia 1 deri 3].
 */
type Row = [string, [string, string, string, string], 0 | 1 | 2 | 3, 1 | 2 | 3];

export const QUESTION_BANK: Record<CompetitionCategory, Row[]> = {
  general: [
    ["Sa kontinente ka Toka sipas ndarjes më të zakonshme?", ["5", "6", "7", "8"], 2, 1],
    ["Cili është oqeani më i madh në botë?", ["Atlantiku", "Indiani", "Arktiku", "Paqësori"], 3, 1],
    ["Sa minuta ka një ditë?", ["1.440", "1.240", "3.600", "86.400"], 0, 2],
    ["Cila planet njihet si «planeti i kuq»?", ["Venusi", "Marsi", "Jupiteri", "Saturni"], 1, 1],
    ["Kush e pikturoi «Mona Lizën»?", ["Mikelanxhelo", "Rafaeli", "Leonardo da Vinçi", "Van Gogu"], 2, 1],
    ["Sa kocka ka trupi i një të rrituri?", ["186", "206", "226", "306"], 1, 2],
    ["Cili element kimik ka simbolin «O»?", ["Ari", "Osmiumi", "Oksigjeni", "Oksidi"], 2, 1],
    ["Sa vjet ka një shekull?", ["10", "50", "100", "1000"], 2, 1],
  ],
  mathematics: [
    ["Sa është 15% e 200?", ["20", "25", "30", "35"], 2, 1],
    ["Cila është rrënja katrore e 144?", ["11", "12", "13", "14"], 1, 1],
    ["Zgjidh: 3x − 7 = 11. Sa është x?", ["4", "5", "6", "7"], 2, 1],
    ["Derivati i x² është:", ["x", "2x", "x²/2", "2"], 1, 2],
    ["Sa është shuma e këndeve të brendshme të një trekëndëshi?", ["90°", "180°", "270°", "360°"], 1, 1],
    ["Sa është 2 në fuqinë e 10-të?", ["512", "1.000", "1.024", "2.048"], 2, 2],
    ["Probabiliteti që një monedhë të bjerë dy herë rresht «stemë» është:", ["1/2", "1/3", "1/4", "1/8"], 2, 2],
    ["Integrali i 2x sipas x është:", ["x² + C", "2x² + C", "x + C", "2 + C"], 0, 3],
  ],
  economics: [
    ["Inflacioni është:", ["Rënia e çmimeve", "Rritja e përgjithshme e çmimeve", "Rritja e pagave", "Rënia e prodhimit"], 1, 1],
    ["BPV (GDP) mat:", ["Borxhin e shtetit", "Vlerën e mallrave dhe shërbimeve të prodhuara në një vend", "Eksportet", "Rezervat e bankës qendrore"], 1, 1],
    ["Kur çmimi rritet dhe gjërat e tjera mbeten njësoj, sasia e kërkuar zakonisht:", ["Rritet", "Bie", "Mbetet njësoj", "Dyfishohet"], 1, 1],
    ["Cili institucion drejton politikën monetare në eurozonë?", ["Banka Botërore", "FMN", "Banka Qendrore Evropiane", "Komisioni Evropian"], 2, 2],
    ["Monedha zyrtare e përdorur në Kosovë është:", ["Dinari", "Lekë", "Euro", "Dollari"], 2, 1],
    ["Kostoja e alternativës së humbur quhet:", ["Kosto fikse", "Kosto oportune", "Kosto marxhinale", "Kosto e zhytur"], 1, 2],
    ["Kur kërkesa rritet dhe oferta mbetet njësoj, çmimi i ekuilibrit:", ["Bie", "Rritet", "Nuk ndryshon", "Bëhet zero"], 1, 2],
    ["Elasticiteti i kërkesës mat:", ["Sa ndryshon sasia e kërkuar kur ndryshon çmimi", "Sa fitim ka firma", "Sa rritet oferta", "Sa taksa paguhen"], 0, 3],
  ],
  business: [
    ["Analiza SWOT shqyrton:", ["Shitjet, punëtorët, objektivat, taksat", "Pikat e forta, dobësitë, mundësitë, kërcënimet", "Stoqet, pagat, orët, transportin", "Vetëm konkurrentët"], 1, 1],
    ["Fitimi bruto llogaritet si:", ["Të ardhurat minus kostoja e mallrave të shitura", "Të ardhurat plus taksat", "Asetet minus detyrimet", "Shitjet minus pagat e menaxherëve"], 0, 2],
    ["Pika e break-even është kur:", ["Fitimi është maksimal", "Të ardhurat barazohen me kostot", "Shitjet dyfishohen", "Firma hyn në bursë"], 1, 2],
    ["«B2B» do të thotë shitje:", ["Nga biznesi te konsumatori", "Nga biznesi te biznesi", "Nga banka te biznesi", "Nga buxheti te biznesi"], 1, 1],
    ["Cili nga këta është një aset?", ["Kredia bankare", "Paratë në llogari", "Pagat e papaguara", "Taksat e detyruara"], 1, 2],
    ["«4P» e marketingut janë:", ["Produkti, çmimi, vendi, promovimi", "Plani, personeli, prodhimi, profiti", "Partneri, publiku, politika, projekti", "Pagesa, pritja, pakoja, prezantimi"], 0, 1],
    ["Bilanci i gjendjes tregon:", ["Të ardhurat e vitit", "Asetet, detyrimet dhe kapitalin në një çast", "Vetëm shitjet", "Rrjedhën e parave gjatë një muaji"], 1, 3],
    ["Një startup zakonisht financohet në fillim nga:", ["Dividendët", "Investitorët engjëj dhe kapitali sipërmarrës", "Taksat", "Obligacionet shtetërore"], 1, 2],
  ],
  agriculture: [
    ["Cili element ushqyes e forcon më shumë rritjen e gjetheve të bimës?", ["Azoti", "Hekuri", "Kalciumi", "Squfuri"], 0, 2],
    ["Rotacioni i kulturave shërben kryesisht për:", ["Të rritur çmimin", "Të ruajtur pjellorinë e tokës dhe për të ulur dëmtuesit", "Të shpejtuar vjeljen", "Të kursyer ujin e pijshëm"], 1, 1],
    ["Fotosinteza ndodh kryesisht në:", ["Rrënjë", "Gjethe", "Lule", "Fara"], 1, 1],
    ["Ujitja me pika është e dobishme sepse:", ["Përdor më shumë ujë", "E çon ujin drejt te rrënja dhe kursen ujë", "E ftoh tokën", "Nuk kërkon tuba"], 1, 1],
    ["Bimët bishtajore (fasulja, bizelja) e pasurojnë tokën me:", ["Kalium", "Fosfor", "Azot", "Natrium"], 2, 2],
    ["pH ideal për shumicën e kulturave është afërsisht:", ["3 deri 4", "6 deri 7", "9 deri 10", "12"], 1, 2],
    ["Plehu organik më i zakonshëm në fermë është:", ["Ureja", "Plehu i kafshëve", "Amoniaku", "Squfuri"], 1, 1],
    ["Mbrojtja e integruar e bimëve përdor pesticidet kimike:", ["Gjithmonë të parat", "Si hap i fundit, pas metodave të tjera", "Asnjëherë", "Vetëm në dimër"], 1, 3],
  ],
  computer_science: [
    ["Sa bit ka një bajt?", ["4", "8", "16", "32"], 1, 1],
    ["Cila strukturë të dhënash funksionon sipas parimit LIFO?", ["Radha (queue)", "Stiva (stack)", "Pema", "Grafi"], 1, 1],
    ["Kompleksiteti i kërkimit binar në një listë të renditur është:", ["O(n)", "O(log n)", "O(n²)", "O(1)"], 1, 2],
    ["HTML është:", ["Gjuhë programimi", "Gjuhë shënjimi për faqet web", "Bazë të dhënash", "Sistem operativ"], 1, 1],
    ["Cili protokoll përdoret për faqet web të sigurta?", ["FTP", "HTTP", "HTTPS", "SMTP"], 2, 1],
    ["SQL përdoret kryesisht për:", ["Dizajn grafik", "Punë me baza të dhënash", "Rrjete sociale", "Kompresim videosh"], 1, 1],
    ["Numri binar 1010 në dhjetor është:", ["8", "10", "12", "20"], 1, 2],
    ["Cila nga këto është gjuhë me tipizim statik?", ["Python", "JavaScript", "Java", "Ruby"], 2, 3],
  ],
  engineering: [
    ["Njësia e forcës në sistemin SI është:", ["Xhauli", "Njutoni", "Vati", "Paskali"], 1, 1],
    ["Ligji i Ohmit shprehet si:", ["U = I · R", "P = U · I²", "F = m · a", "E = m · c²"], 0, 1],
    ["Fuqia elektrike matet në:", ["Volt", "Amper", "Vat", "Om"], 2, 1],
    ["Betoni i armuar përmban:", ["Vetëm çimento", "Beton me shufra çeliku", "Beton me dru", "Beton me plastikë"], 1, 1],
    ["Një lever (levë) i klasës së parë e ka pikën e mbështetjes:", ["Në fund", "Mes forcës dhe ngarkesës", "Jashtë levës", "Mbi ngarkesë"], 1, 2],
    ["Rendimenti i një makine është gjithmonë:", ["Mbi 100%", "Saktësisht 100%", "Nën 100%", "Negativ"], 2, 2],
    ["Në qarkun seri, rryma nëpër çdo element është:", ["E njëjtë", "E ndryshme", "Zero", "E kundërt"], 0, 2],
    ["Moduli i Jungut përshkruan:", ["Ngurtësinë e materialit ndaj deformimit elastik", "Përçueshmërinë elektrike", "Dendësinë", "Temperaturën e shkrirjes"], 0, 3],
  ],
  medicine: [
    ["Sa dhoma ka zemra e njeriut?", ["2", "3", "4", "5"], 2, 1],
    ["Cili organ prodhon insulinën?", ["Mëlçia", "Pankreasi", "Veshkat", "Stomaku"], 1, 1],
    ["Qelizat e kuqe të gjakut bartin kryesisht:", ["Oksigjen", "Hormone", "Antitrupa", "Yndyrë"], 0, 1],
    ["Temperatura normale e trupit është afërsisht:", ["35 °C", "37 °C", "39 °C", "41 °C"], 1, 1],
    ["Vitamina D prodhohet në lëkurë nën ndikimin e:", ["Ujit", "Rrezeve të diellit", "Proteinave", "Gjumit"], 1, 1],
    ["Organi më i madh i trupit është:", ["Mëlçia", "Truri", "Lëkura", "Mushkëritë"], 2, 2],
    ["Antibiotikët veprojnë kundër:", ["Viruseve", "Baktereve", "Alergjive", "Të gjitha sëmundjeve"], 1, 2],
    ["Cili lloj gjaku quhet «dhurues universal» i qelizave të kuqe?", ["A+", "B−", "AB+", "0−"], 3, 3],
  ],
  languages: [
    ["Sa shkronja ka alfabeti i shqipes?", ["26", "30", "36", "40"], 2, 1],
    ["Si thuhet «faleminderit» në gjermanisht?", ["Danke", "Bitte", "Merci", "Grazie"], 0, 1],
    ["Forma e shkuar e «go» në anglisht është:", ["Goed", "Went", "Gone", "Going"], 1, 1],
    ["«Bonjour» është përshëndetje në:", ["Italisht", "Spanjisht", "Frëngjisht", "Portugalisht"], 2, 1],
    ["Cila fjalë është emër në shqip?", ["Shpejt", "Libër", "Bukur", "Vrapoj"], 1, 1],
    ["Si thuhet «unë jam student» në anglisht?", ["I am a student", "I is student", "Me student am", "I be student"], 0, 1],
    ["Shumësi i «man» në anglisht është:", ["Mans", "Men", "Mens", "Manes"], 1, 2],
    ["Në shqip, «ç» dhe «xh» janë:", ["Zanore", "Bashkëtingëllore", "Shenja pikësimi", "Numra"], 1, 2],
  ],
  history: [
    ["Në cilin vit u shpall Pavarësia e Shqipërisë?", ["1878", "1912", "1920", "1944"], 1, 1],
    ["Kosova shpalli pavarësinë më:", ["17 shkurt 2008", "28 nëntor 2008", "17 shkurt 1999", "12 qershor 1999"], 0, 1],
    ["Lidhja e Prizrenit u themelua në vitin:", ["1878", "1881", "1908", "1912"], 0, 2],
    ["Heroi kombëtar i shqiptarëve që luftoi kundër Perandorisë Osmane në shekullin XV është:", ["Ismail Qemali", "Gjergj Kastrioti Skënderbeu", "Naim Frashëri", "Isa Boletini"], 1, 1],
    ["Lufta e Dytë Botërore përfundoi në Evropë në vitin:", ["1918", "1939", "1945", "1950"], 2, 1],
    ["Kongresi i Manastirit (1908) vendosi:", ["Flamurin", "Alfabetin e gjuhës shqipe", "Kryeqytetin", "Kufijtë"], 1, 2],
    ["Muri i Berlinit ra në vitin:", ["1961", "1985", "1989", "1991"], 2, 2],
    ["Perandoria Romake Perëndimore ra në vitin:", ["476", "1453", "395", "800"], 0, 3],
  ],
  geography: [
    ["Kryeqyteti i Kosovës është:", ["Prizreni", "Prishtina", "Peja", "Mitrovica"], 1, 1],
    ["Lumi më i gjatë në botë sipas shumicës së matjeve është:", ["Amazona", "Nili", "Danubi", "Misisipi"], 1, 2],
    ["Maja më e lartë në Kosovë është:", ["Gjeravica", "Pashtriku", "Luboteni", "Koritniku"], 0, 2],
    ["Cili shtet ka popullsinë më të madhe në botë sipas numërimeve të fundit?", ["SHBA", "Indonezia", "India", "Rusia"], 2, 2],
    ["Deti Adriatik laget nga:", ["Vetëm Italia", "Italia, Shqipëria, Mali i Zi, Kroacia dhe të tjera", "Vetëm Greqia", "Turqia"], 1, 1],
    ["Cili është kontinenti më i madh?", ["Afrika", "Azia", "Evropa", "Amerika"], 1, 1],
    ["Ekuatori e ndan Tokën në:", ["Lindje dhe perëndim", "Hemisferën veriore dhe jugore", "Kontinente", "Zona kohore"], 1, 1],
    ["Liqeni i Ohrit ndahet mes:", ["Shqipërisë dhe Maqedonisë së Veriut", "Kosovës dhe Shqipërisë", "Greqisë dhe Shqipërisë", "Malit të Zi dhe Shqipërisë"], 0, 2],
  ],
  science: [
    ["Formula kimike e ujit është:", ["CO₂", "H₂O", "O₂", "NaCl"], 1, 1],
    ["Shpejtësia e dritës në vakum është afërsisht:", ["300.000 km/s", "30.000 km/s", "3.000 km/s", "300 km/s"], 0, 2],
    ["Njësia bazë e jetës është:", ["Atomi", "Qeliza", "Organi", "Molekula"], 1, 1],
    ["ADN-ja ndodhet kryesisht në:", ["Bërthamën e qelizës", "Membranë", "Ribozome", "Vakuolë"], 0, 2],
    ["Uji vlon në nivel të detit në:", ["90 °C", "100 °C", "110 °C", "80 °C"], 1, 1],
    ["Graviteti në Tokë shkakton nxitim afërsisht:", ["1,6 m/s²", "9,8 m/s²", "15 m/s²", "3,7 m/s²"], 1, 2],
    ["Cila pjesë e atomit ka ngarkesë negative?", ["Protoni", "Neutroni", "Elektroni", "Bërthama"], 2, 1],
    ["pH i një tretësire neutrale është:", ["0", "5", "7", "14"], 2, 1],
  ],
  technology: [
    ["Çfarë do të thotë «AI»?", ["Internet i avancuar", "Inteligjencë artificiale", "Informacion automatik", "Aplikacion interaktiv"], 1, 1],
    ["Cloud computing do të thotë:", ["Llogaritje me dronë", "Përdorim i burimeve kompjuterike përmes internetit", "Ruajtje vetëm në USB", "Rrjet pa energji"], 1, 1],
    ["Autentikimi me dy faktorë shton:", ["Një fjalëkalim të dytë të njëjtë", "Një hap të dytë verifikimi, p.sh. kod në telefon", "Një llogari të dytë", "Një emër përdoruesi të ri"], 1, 1],
    ["Phishing-u është:", ["Një lloj antivirusi", "Mashtrim që synon të vjedhë të dhëna duke u shtirur si burim i besueshëm", "Protokoll interneti", "Program për foto"], 1, 1],
    ["IPv4 përdor adresa me gjatësi:", ["16 bit", "32 bit", "64 bit", "128 bit"], 1, 2],
    ["Cila nga këto është kujtesë e përhershme?", ["RAM", "SSD", "Cache L1", "Regjistri i CPU-së"], 1, 2],
    ["Open source do të thotë që kodi burimor:", ["Është sekret", "Është publik dhe mund të studiohet e ndryshohet sipas licencës", "Shitet vetëm", "Nuk ka licencë"], 1, 1],
    ["Blockchain-i ruan të dhënat në:", ["Një server të vetëm", "Blloqe të lidhura dhe të shpërndara në shumë nyje", "Vetëm në telefon", "Letër"], 1, 3],
  ],
  literature: [
    ["Kush e shkroi «Lahuta e Malcís»?", ["Naim Frashëri", "Gjergj Fishta", "Migjeni", "Ismail Kadare"], 1, 2],
    ["«Gjenerali i ushtrisë së vdekur» është vepër e:", ["Dritëro Agollit", "Ismail Kadaresë", "Fatos Arapit", "Martin Camajt"], 1, 1],
    ["Kush e shkroi «Romeo dhe Zhuljeta»?", ["Çarls Dikens", "Uilliam Shekspir", "Lev Tolstoi", "Viktor Hygo"], 1, 1],
    ["«Bagëti e Bujqësi» është poemë e:", ["Naim Frashërit", "Andon Zako Çajupit", "Ndre Mjedës", "Asdrenit"], 0, 2],
    ["Migjeni ishte pseudonim i:", ["Millosh Gjergj Nikollës", "Mitrush Kutelit", "Lasgush Poradecit", "Faik Konicës"], 0, 2],
    ["«Don Kishoti» u shkrua nga:", ["Servantesi", "Dante", "Gëte", "Molieri"], 0, 1],
    ["Një sonet ka zakonisht:", ["10 vargje", "12 vargje", "14 vargje", "16 vargje"], 2, 2],
    ["Kush është autori i «Komedisë Hyjnore»?", ["Petrarka", "Dante Aligieri", "Bokaçio", "Ariosto"], 1, 1],
  ],
  university_life: [
    ["Çfarë shënon ECTS?", ["Numrin e provimeve", "Kreditë evropiane për ngarkesën e studimit", "Notën mesatare", "Orët e ligjëratave në javë"], 1, 1],
    ["Sa kredi ECTS ka zakonisht një vit akademik me kohë të plotë?", ["30", "45", "60", "90"], 2, 1],
    ["Plagjiatura është:", ["Citimi i saktë i burimeve", "Paraqitja e punës së tjetrit si të tuajën", "Shkrimi në grup", "Përkthimi i një teksti"], 1, 1],
    ["Erasmus+ është program i BE-së për:", ["Punësim", "Shkëmbime studimi dhe trajnimi", "Kredi studentore", "Sport"], 1, 1],
    ["Teknika Pomodoro e ndan kohën e studimit në blloqe prej rreth:", ["5 minutash", "25 minutash", "60 minutash", "2 orësh"], 1, 1],
    ["Një abstrakt i punimit shkencor është:", ["Lista e burimeve", "Përmbledhje e shkurtër e punimit", "Kapitulli i fundit", "Falënderimet"], 1, 1],
    ["Citimi APA e vendos në tekst:", ["Vetëm titullin", "Mbiemrin e autorit dhe vitin", "Numrin e faqes së parë", "Emrin e botuesit"], 1, 2],
    ["Përsëritja e shpërndarë (spaced repetition) do të thotë:", ["Të mësosh gjithçka natën para provimit", "Të përsëritësh në intervale që rriten me kohën", "Të lexosh vetëm një herë", "Të studiosh vetëm në grup"], 1, 2],
  ],
};
